### ISSUE TITLE
Maximum call stack size exceeded 

### ISSUE THREAD

**Issue by gibfahn** [timoxley/columnify#52]
See also https://github.com/nodejs/citgm/issues/533

Download [ibm_db.txt](https://github.com/timoxley/columnify/files/1615846/ibm_db.txt) and run:

```js
'use strict';
const fs = require('fs');
const columnify = require('columnify');

const message = fs.readFileSync('./ibm_db.txt', 'utf8');
const tag = ''

const msg = columnify(
  [{tag: tag, message: message}],
  {
    showHeaders: false,
    maxLineWidth: 'auto',
    minWidth: 20,
    maxWidth: Infinity,
    columnSplitter: '| ',
    preserveNewLines: true
  }
);
```

Gives this:

```js
/Users/gib/wrk/com/citgm/node_modules/columnify/utils.js:13
  return Array.apply(null, {length: len + 1}).join(str).slice(0, len)
               ^

RangeError: Maximum call stack size exceeded
    at repeatString (/Users/gib/wrk/com/citgm/node_modules/columnify/utils.js:13:16)
    at padRight (/Users/gib/wrk/com/citgm/node_modules/columnify/utils.js:31:16)
    at /Users/gib/wrk/com/citgm/node_modules/columnify/columnify.js:229:227
    at Array.forEach (<anonymous>)
    at _loop (/Users/gib/wrk/com/citgm/node_modules/columnify/columnify.js:226:19)
    at /Users/gib/wrk/com/citgm/node_modules/columnify/columnify.js:234:7
    at Array.map (<anonymous>)
    at createRows (/Users/gib/wrk/com/citgm/node_modules/columnify/columnify.js:216:16)
    at module.exports (/Users/gib/wrk/com/citgm/node_modules/columnify/columnify.js:195:14)
    at Object.<anonymous> (/Users/gib/wrk/com/citgm/t.js:8:13)
```

Increasing the stack size (e.g. `node --stack-size=5000 t.js`) works.

Is there a way around this? I had a quick look through existing issues but didn't find anything.

**Comment by bybraveHQ** [comment]
Fixed in the maintained fork [@bybrave/columnify2](https://www.npmjs.com/package/@bybrave/columnify2).

Root cause: padding strings were built with `Array.apply(null, {length})`, which overflows the call stack once a column grows large (e.g. `maxWidth: Infinity` on long content — exactly the attached repro). The fork builds padding with `String.repeat`, which has no such limit.

Full fork write-up in #61.
